/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mec.a.lab06;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.concurrent.atomic.AtomicInteger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Estudiante
 */
public class TragaMonedas extends javax.swing.JFrame {

    /**
     * Creates new form TragaMonedas
     */
    AtomicInteger atm = new AtomicInteger();
    Random rand = new Random();
    public TragaMonedas() {
        initComponents();
        jLabel1.setIcon(new ImageIcon("image/Tragamonedas_Fondo.jpg"));
        
    }
    private static BufferedImage cargarImagen(String ruta) {
        try {
            return ImageIO.read(new File(ruta));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Img1 = new javax.swing.JLabel();
        Img2 = new javax.swing.JLabel();
        Img3 = new javax.swing.JLabel();
        Girar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(612, 419));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Img1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        jPanel1.add(Img2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));
        jPanel1.add(Img3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        Girar.setBackground(new java.awt.Color(255, 204, 102));
        Girar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GirarActionPerformed(evt);
            }
        });
        jPanel1.add(Girar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 40, 20));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GirarActionPerformed
        atm.set(1);
        TimerTask tmt = new TimerTask() {
		    @Override
		    public void run(){
                       int x1 = rand.nextInt(4), y1 = rand.nextInt(4),
                           x2 = rand.nextInt(4), y2 = rand.nextInt(4),
                           x3 = rand.nextInt(4), y3 = rand.nextInt(4);
                       //int x1=2,x2=2,x3=2,y1=1,y2=1,y3=1;
                       //La línea anterior es para comprobar que emite el mensaje de felicitaciones
                       atm.set(atm.get()*2);		       
                       BufferedImage imagenOriginal = cargarImagen("image/TragamonedasIMG.jpg");
                       BufferedImage parte1 = imagenOriginal.getSubimage(102*x1, 87*y1, 102, 87);
                       BufferedImage parte2 = imagenOriginal.getSubimage(102*x2, 87*y2, 102, 87);
                       BufferedImage parte3 = imagenOriginal.getSubimage(102*x3, 87*y3, 102, 87);
                       Img1.setIcon(new ImageIcon(parte1));
                       Img2.setIcon(new ImageIcon(parte2));
                       Img3.setIcon(new ImageIcon(parte3));
		       if (atm.get() > 120000){
                           if(x1 == x2 && x2 == x3){
                                if(y1 == y2 && y2 == y3)
                                    JOptionPane.showMessageDialog(null, "Felicitaciones ¡¡HA GANADO!!");
                           }
		        cancel();
                       }
                       try{
                           Thread.sleep(atm.get()/90);
                       } catch(InterruptedException e){ }
		    }
		};
		Timer timer = new Timer();
		timer.scheduleAtFixedRate(tmt, 1000,90);
    
                
    }//GEN-LAST:event_GirarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TragaMonedas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TragaMonedas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Girar;
    private javax.swing.JLabel Img1;
    private javax.swing.JLabel Img2;
    private javax.swing.JLabel Img3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
